### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by melbasuonyy** [Ozencb/yts-scraper#2]
Hello 
I'm getting the below error can you check the reason

HTTP Error: 503 Server Error: Service Temporarily Unavailable for url: https://yts.mx/api/v2/list_movies.json?quality=1080p&genre=all&minimum_rating=0&sort_by=date_added&order_by=desc&limit=50&page=

**Comment by ozencb** [comment]
What does that URL show when you launch it in a browser?

Edit: It seems the API is down at the moment. 

Edit2: The API works fine on browsers but it denies HTTP requests from the script. I will have to look into it

**Comment by melbasuonyy** [comment]
Yes i think yts api is down from browser is working 

Thanks for your kind support boss

**Comment by ozencb** [comment]
I thought it was down at first but I was wrong. YTS servers or their DDoS protection services deny GET requests because the script is downloading huge amounts of data from their servers in a short amount of time. This was fine before I implemented multiprocessing because the download process was much, much slower so it did not raise any flags.

I will try to implement a user-agent rotation but it most likely will not be enough, you might need an IP change or a modem reset.

**Comment by ozencb** [comment]
I pushed an update to repo. It does work for me ATM. Can you try it again after restarting your modem?

**Comment by melbasuonyy** [comment]
worked and downloaded 1000 file then stuck again. I think if you removed multiprocessing  will be better (my opinion) 

thanks

**Comment by ozencb** [comment]
Alright, I made multiprocessing optional now

**Comment by melbasuonyy** [comment]
working perfect thanks
