### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by zool44** [Ozencb/yts-scraper#3]
Hi, loving this tool, working really well.

I'm getting the error below, always failing at the same 1965 torrent using parameters:
yts-scraper -q 1080p -b -o "yify_movies" -c genre -r 6

Was wondering if there was any way to continue onto the next torrent if yify has a problem?

Downloaded The Flintstones Meet Rockula and Frankenstone (1979) 1080P
Downloading:  13%|███                 | 1147/9103 [30:53<3:57:00,  1.79s/Files]
Traceback (most recent call last):
  File "C:\Users\pally_2\AppData\Local\Programs\Python\Python37\lib\site-package
s\yts_scraper-0.1.1-py3.7.egg\yts_scraper\main.py", line 106, in main
    scraper.download()
  File "C:\Users\pally_2\AppData\Local\Programs\Python\Python37\lib\site-package
s\yts_scraper-0.1.1-py3.7.egg\yts_scraper\scraper.py", line 272, in download
    self.__initialize_download()
  File "C:\Users\pally_2\AppData\Local\Programs\Python\Python37\lib\site-package
s\yts_scraper-0.1.1-py3.7.egg\yts_scraper\scraper.py", line 159, in __initialize
_download
    self.__filter_torrents(movie)
  File "C:\Users\pally_2\AppData\Local\Programs\Python\Python37\lib\site-package
s\yts_scraper-0.1.1-py3.7.egg\yts_scraper\scraper.py", line 199, in __filter_tor
rents
    is_download_successful = self.__download_file(bin_content_tor, bin_content_i
mg, path, movie_name, movie_id)
  File "C:\Users\pally_2\AppData\Local\Programs\Python\Python37\lib\site-package
s\yts_scraper-0.1.1-py3.7.egg\yts_scraper\scraper.py", line 244, in __download_f
ile
    with open((path + '.torrent'), 'wb') as t:
FileNotFoundError: [Errno 2] No such file or directory: './yify_movies/Adventure
/Those Magnificent Men in Their Flying Machines or How I Flew from London to Par
is in 25 hours 11 minutes (1965)\\Those Magnificent Men in Their Flying Machines
 or How I Flew from London to Paris in 25 hours 11 minutes (1965) 1080p.torrent'

**Comment by ozencb** [comment]
Hmm, the issue might have something to do with Windows' maximum path character length limit. I am looking into it

**Comment by ozencb** [comment]
As I have said in the previous comment, Windows NTFS filesystem has a 260 character path limit and the problem is likely deriving from that limit. I had that limit disabled on my system and I could get Python to write that file on my machine so I enabled the limit again and got the same error you got.

I looked for a programmatic solution on Python but few solutions I found does not seem to be reliable so the only solution is to disable path length limit.

Please refer to this guide to do so:
[Disable path length limit](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters)

and if you ever reinstall Python, make sure that you hit this button: 
[Disable path length limit](https://i.stack.imgur.com/r6XEh.jpg)
