### ISSUE TITLE
All torrents are scraped

### ISSUE THREAD

**Issue by Azertyfied** [Ozencb/yts-scraper#7]
First of all I need to point out that I'm completely new to programming and consequentially to GitHub, so I'm sorry if this is not the right way to ask for assistance, if at all possible.

I was able to run this beautiful command of yours last week without any issues. However upon trying again today, I was unable to filter out the torrent files eventhough I was using the -q 1080p and -r 8 options in my command. For some reason the command scrapes or checks 16912 files (which are all of them, I reckon). So literally all torrent files are scraped. 

Any idea/ suggestions on how to fix this?

![image](https://user-images.githubusercontent.com/64867960/81112791-7ea93d00-8f1f-11ea-9593-54cd05ad7894.png)

**Comment by ozencb** [comment]
Hello! Thank you for reporting this bug. It seems I broke base API URL by trying to make it look prettier on code :) 

A fix has been pushed in this commit and everything should be working fine now: https://github.com/Ozencb/yts-scraper/commit/b6389d4f1c98640f80f266451f7458d43879ffbd

Have a nice day!

**Comment by ozencb** [comment]
Oh, since you are new to programming and I presume you want to tinker with these projects I'd like to explain what the problem was and how I fixed it. Mind you that I have been programming for 2 or maybe 3 years so I am not an expert on anything yet but this particular issue was pretty simple :)

So, if you click on the Github issue link that I provided in the comment above, you will see a red section and a green section. Reds are the lines that existed in the version before (so that has been removed) and greens are the ones that has been added. 

You can see that I did not change anything significant but instead collapsed the URL string into a single line. I did so because in Python, you can make a multi-line string by enclosing the string with `'''` characters. This does work fine on things like printing stuff on the terminal but not so well on things like URLs (which I just figured out, haha) because Python treats these multiline strings "as is", so it takes the whole thing as a block with new lines and everything.

You can see that I enclosed the API URL in multi-line quotation marks `'''` and broke the base URL into various lines to make it easier to read but caused it to take only the first line of that string (`https://yts.mx/api/v2/list_movies.json?`), which returns every movie in YTS's database. So, yeah... That was a problem :)

**Comment by Azertyfied** [comment]
Hi

You're the real MVP! :p
Thank you so much, for both the fix and the information above!
You are most kind, sir! ;)

Take care!

Op di 5 mei 2020 om 23:05 schreef Özenç Bilgili <notifications@github.com>:
