### ISSUE TITLE
"Not a valid bencoded string."

### ISSUE THREAD

**Issue by Azertyfied** [Ozencb/yts-scraper#8]
I'm sorry for asking for assistance once again, but I just can't succeed in downloading all the .torrent files based on my query [yts-scraper -q 1080p -r 7].

I try using the "yts-scraper -q 1080p -r 7" query, which works fine at first, but it always stops after a certain percentage, 19% in this case. I can never get to 100%, not with nor without the <-m> addition.

Since I didn't want to run the query again starting from page 1, I wanted to use your <-p> addition.
But for some reason the pages in CMD differ from the ones on the actual https://yts.mx/ site.
That isn't a huge issue however, since I can always go back or ahead a few pages to pick up where the scraper left off.

The main problem though is that I couldn't get any of the .torrent files to open after completion.
I always get an error in Deluge, saying "not a valid bencoded string".
Could you maybe try to run the entire <yts-scraper -q 1080p -r 7> command to see what happens to you?
It would help if you could filter out certain years to narrow down the search. So an extensions to the <-y> addition where you could set both a start and end year. Is that possible? 

Regardless of the outcome, thanks again for taking your time to look into this! :) 

![1](https://user-images.githubusercontent.com/64867960/81494645-c5de5780-92aa-11ea-9c6a-f789e61626b4.PNG)
![2](https://user-images.githubusercontent.com/64867960/81494647-c676ee00-92aa-11ea-9842-9e12cccf81f9.PNG)

**Comment by ozencb** [comment]
Hello, there! Thank you for the feedback.

I started working on this bug but I reckon it will take some time to pinpoint the issue because at this moment YTS API is behaving rather oddly. I do not really know what is going on with it so I will have to look deeper into it.

It is also weird that it stops suddenly without any errors. I mean, if it was a broken URL or empty binary content it would result in an error, not a sudden termination. So, it seems we are in for a ride but it is going to be fun 😊 

Regarding the issue with torrent files not opening; I only test these on Qbittorrent and they all work fine. Did you try another torrent client? Are all of them broken? I also heard that in some countries ISPs corrupt torrent files on purpose because of government restrictions so can you try using a VPN?

Best regards!

**Comment by Azertyfied** [comment]
Hi

Thanks for picking this up so quickly!
I haven't tried another torrent client yet, I'll make sure to give that a try!
I do use a VPN service already, but I'll toy around with that as well!

Have fun! :p

**Comment by Azertyfied** [comment]
![image](https://user-images.githubusercontent.com/64867960/81589955-58215100-93ba-11ea-9f27-83cc55fa510c.png)
Just gave it try with qBittorrent and with several .torrent files, but the issue seems to persist.

**Comment by ozencb** [comment]
Have you tried a different VPN, preferably a tunnel to a country with looser torrenting restrictions?

**Comment by Azertyfied** [comment]
When trying a VPN based in for example India or Brazil instead of a western country, it does seem to make a difference. So in other words, the .torrent files are indeed still valid when using those countries. Good thinking! :p

**Comment by ozencb** [comment]
I am glad that worked you :) Since this particular issue is related to ISP's file corruption practices and not to the script itself, I will close it. I will work on the other problem when I have time.

Best regards
